FROM rabbitmq:3.13-management

RUN apt-get update && apt-get install -y curl

RUN curl -L -o $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange.ez \
https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.13.0/rabbitmq_delayed_message_exchange-3.13.0.ez

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange